#!/usr/bin/env bash

sudo apt update
sudo apt upgrade -y

sudo add-apt-repository ppa:mmstick76/alacritty -y

sudo apt install alacritty make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libedit-dev libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git zsh -y

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

curl -fsSL https://starship.rs/install.sh | bash
